# Generated by Django 4.2.29 on 2026-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('upload', 'File Upload'), ('url', 'Image URL'), ('camera', 'Live Camera')], max_length=10)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='detections/input/')),
                ('input_image_url', models.URLField(blank=True, null=True)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='detections/output/')),
                ('pothole_count', models.PositiveIntegerField(default=0)),
                ('detections_json', models.JSONField(default=list)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('verified', 'Verified'), ('repaired', 'Repaired'), ('false_positive', 'False Positive')], default='detected', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'db_table': 'detection_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PotholeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('pending', 'Pending')], default='reported', max_length=20)),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pothole Location',
                'verbose_name_plural': 'Pothole Locations',
                'db_table': 'pothole_locations',
                'ordering': ['-last_detected'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('registered', 'Registered User'), ('admin', 'Admin')], default='registered', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='detection_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='detection_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
